# Generated by Django 6.0 on 2025-12-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0005_alter_manufacturer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Product Id')),
                ('name', models.CharField(max_length=255, verbose_name='Medicine Name')),
                ('genericName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Generic Name')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status')),
                ('comp_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comp Code')),
                ('mod_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mod Code')),
                ('user_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Code')),
                ('mfg_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='MFG Code')),
                ('rack_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rack Code')),
                ('packing_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Packing Code')),
                ('purchase_tax_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchase Tax Code')),
                ('purchase_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_discount_mode', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=20, null=True)),
                ('sales_tax_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sales Tax Code')),
                ('sales_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_discount_mode', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=20, null=True)),
                ('last_update', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Update')),
                ('del_flag', models.CharField(default='no', max_length=5, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='manufacturer.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
