# Generated by Django 6.0 on 2025-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Powder', 'Powder'), ('Cream', 'Cream'), ('Gel', 'Gel'), ('Others', 'Others')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Low', 'Low'), ('Available', 'Available')], default='Available', max_length=20, verbose_name='Status'),
        ),
    ]
