# Generated by Django 6.0 on 2025-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Powder', 'Powder'), ('Cream', 'Cream'), ('Gel', 'Gel'), ('Others', 'Others')], default='Tablet', max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_discount_mode',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_discount_mode',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20, null=True),
        ),
    ]
