# Generated by Django 6.0 on 2026-01-03 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_batch_no_alter_product_comp_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='genericName',
            new_name='generic_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comp_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='del_flag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mod_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_code',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=20, unique=True, verbose_name='Product Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment', 'Ointment'), ('Cream', 'Cream'), ('Gel', 'Gel'), ('Drops', 'Drops'), ('Powder', 'Powder'), ('Suspension', 'Suspension'), ('Solution', 'Solution'), ('Inhaler', 'Inhaler'), ('Spray', 'Spray'), ('Lotion', 'Lotion'), ('Granules', 'Granules'), ('Suppository', 'Suppository'), ('Patch', 'Patch'), ('IV Fluid', 'IV Fluid'), ('Sachet', 'Sachet'), ('Kit', 'Kit'), ('Medical Device', 'Medical Device'), ('Nutraceutical', 'Nutraceutical'), ('Ayurvedic', 'Ayurvedic'), ('Homeopathic', 'Homeopathic'), ('Surgical', 'Surgical'), ('Others', 'Others')], default='Tablet', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_discount_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_discount_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20),
        ),
    ]
