# Generated by Django 6.0 on 2025-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('mfg_name', models.CharField(max_length=255)),
                ('mfg_short', models.CharField(blank=True, max_length=50, null=True)),
                ('mr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mr_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mfg_address', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_discount_mode', models.CharField(blank=True, choices=[('%', 'Percentage'), ('Flat', 'Flat')], max_length=10, null=True)),
                ('sales_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_discount_mode', models.CharField(blank=True, choices=[('%', 'Percentage'), ('Flat', 'Flat')], max_length=10, null=True)),
                ('mod_code', models.IntegerField()),
            ],
        ),
    ]
