# Generated by Django 6.0 on 2025-12-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_rename_manufacturer_id_manufacturer_mfg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='mfg_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='mfg_short',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
