# Generated by Django 6.0 on 2025-12-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0003_alter_manufacturer_mfg_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['mfg_name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturer',
        ),
    ]
