# Generated by Django 6.0 on 2025-12-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_alter_manufacturer_options_alter_manufacturer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
    ]
