# Generated by Django 6.0 on 2025-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0005_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='mfg_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
