# Generated by Django 6.0 on 2026-01-03 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0006_alter_manufacturer_mfg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['mfg_name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='mfg_id',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='mod_code',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='drug_license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='mfg_code',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=20, unique=True, verbose_name='Manufacturer Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='mfg_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='mfg_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Manufacturer Name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='mfg_short',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Short Code'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='purchase_discount_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='sales_discount_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20),
        ),
    ]
